# 로깅 설정 파일

[logging]
version = 1
disable_existing_loggers = false

[logging.formatters.standard]
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
datefmt = "%Y-%m-%d %H:%M:%S"

[logging.formatters.simple]
format = "%(levelname)s - %(message)s"

[logging.handlers.console]
class = "logging.StreamHandler"
level = "INFO"
formatter = "standard"
stream = "ext://sys.stdout"

[logging.handlers.file]
class = "logging.FileHandler"
level = "DEBUG"
formatter = "standard"
filename = "posture_guardian.log"
encoding = "utf8"
mode = "a"

[logging.loggers.posture_guardian]
level = "DEBUG"
handlers = ["console", "file"]
propagate = false

[logging.root]
level = "INFO"
handlers = ["console", "file"] 